### ISSUE TITLE
build error swc.xml again

### ISSUE THREAD

**Issue by yubi0** [michaelforney/velox#11]
I checked https://github.com/michaelforney/velox/issues/7 and tried to modify the pkgbuild file accordingly. However, this brings me the error
> Package swc was not found in the pkg-config search path.
> Perhaps you should add the directory containing `swc.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'swc' found
>  GEN   protocol/velox-client-protocol.h
> make: *** No rule to make target '/swc.xml', needed by 'protocol/swc-client-protocol.h'.  Stop.

The build error takes up less space now, but is otherwise the same.

For reference, swc.pc is located is /usr/local/lib/pkgconfig/swc.pc

**Comment by michaelforney** [comment]
It sounds like `/usr/local/lib/pkgconfig` is not in your `PKG_CONFIG_PATH`. Though, I would think that you should be installing it in `/usr/lib/pkgconfig` instead. How did you modify the pkgbuild?

You can check `pkg-config --exists --print-errors swc` to check if pkg-config can find it.

**Comment by Kamiyaa** [comment]
Having a similar issue.
I installed wld and swc with PREFIX=/usr.
Then tried installing velox.

```
~ $ make PREFIX=/usr
make: *** No rule to make target '/usr/local/share/swc/swc.xml', needed by 'protocol/swc-client-protocol.h'.  Stop.

~ $ ls /usr/local/share/swc/
ls: cannot access '/usr/local/share/swc/': No such file or directory

~ $ ls /usr/share/swc/
swc.xml

```

**Comment by michaelforney** [comment]
Your swc pkg-config file says it is installed to `/usr/local/share/swc`, but you installed it to `/usr/share/swc`.

I suspect you built swc with the default prefix (`/usr/local`), then installed it with prefix `/usr`.

I suggest setting `PREFIX` in `config.mk`, or always passing the same parameters to `make`.

**Comment by Kamiyaa** [comment]
Thanks, that fixed it!
Though now I'm getting #34.
Guess I'll wait for support for Broadwell and newer generations.
