### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by pickfire** [michaelforney/velox#18]
Hi, I had instaled velox. When I run `swc-launch velox`:
```
Running on /dev/tty3
velox: error while loading shared libraries: libswc.so.0: cannot open shared object file: No such file or directory
Server exited with status 127
Restoring VT to original state
```

**Comment by michaelforney** [comment]
Install swc into a location that your dynamic linker is configured to look for, set the RPATH/RUNPATH for your velox binary, or set LD_LIBRARY_PATH when running velox to the path that contains libswc.so.0.

**Comment by pickfire** [comment]
I had set **RUNPATH** to */usr/local/bin/* and **LD_LIBRARY_PATH** to */usr/local/lib/*, but whe I run `swc-launch velox`:
```
Running on /dev/tty3
velox: error while loading shared libraries: libswc.so.0: cannot open shared object file: No such file or directory
Server exited with status 127
Restoring VT to original state
```

**Comment by pickfire** [comment]
I think this is related to https://github.com/SirCmpwn/sway/issues/143

**Comment by michaelforney** [comment]
Read the error message. velox can't find libswc.so.0. Fix your system configuration so that it can.

**Comment by pickfire** [comment]
I have no idea what should I do now.
![2015-10-13-141905_529x340_scrot](https://cloud.githubusercontent.com/assets/4687791/10447251/7e1daace-71b5-11e5-94db-b93b1dd2a7ee.png)

**Comment by michaelforney** [comment]
Can you run `file /usr/local/lib/libswc.so.0.0`?

Did you export `LD_LIBRARY_PATH`?

If you can't figure it out, maybe do more reading about errors of that type, and play around with `strace` so you can understand what's going on. This is not the place for general linux support.

**Comment by pickfire** [comment]
![2015-10-13-144122_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/10447618/907ab524-71b8-11e5-8512-6f9b83677bad.png)

> If you can't figure it out, maybe do more reading about errors of that type, and play around with strace so you can understand what's going on.

Of course. http://ix.io/loi

**Comment by michaelforney** [comment]
Maybe try `swc-launch -- env LD_LIBRARY_PATH=/usr/local/lib velox`.

If not, for your strace command, use `strace -f` so that the child process is also monitored.

**Comment by pickfire** [comment]
Thanks. It works now, but there is another error related to `wld`:
```
Running on /dev/tty3
[swc:libswc/drm.c:258] ERROR: Could not find DRM device
[swc:libswc/swc.c:124] ERROR: Could not initialize DRM
Server exited with status 1
Restoring VT to original state
```

![2015-10-14-120837_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/10474695/5b565394-726c-11e5-890b-0b67dfee17df.png)

I think I have set the wrong drm driver which is `libdrm` that I had installed, I am not sure what I need to set that.

**Comment by michaelforney** [comment]
Sounds like your system does not have a DRM device.

Since you are on a raspberry pi, are you using a kernel with the [VC4 DRM driver](http://dri.freedesktop.org/wiki/VC4/)?

**Comment by pickfire** [comment]
> Since you are on a raspberry pi, are you using a kernel with the VC4 DRM driver?

Maybe, I am not sure about that but I do have `libdrm` installed.

**Comment by michaelforney** [comment]
libdrm is just a userspace helper library for talking to kernel DRM. If you don't have the right DRM driver enabled in your kernel, there is no way that any DRM-based software can work.

**Comment by pickfire** [comment]
```
[I] ivan@alarmpi ~> sudo find / -name drm -print
/usr/lib/modules/4.1.10-2-ARCH/build/include/drm
/usr/lib/modules/4.1.10-2-ARCH/build/include/uapi/drm
/usr/lib/modules/4.1.10-2-ARCH/build/drivers/gpu/drm
/usr/lib/musl/include/drm
```
I guess I have drm installed, but I am not sure what is the tire name called what driver should I use?

**Comment by michaelforney** [comment]
As stated before... [VC4 DRM driver](http://dri.freedesktop.org/wiki/VC4/).

It's not in the mainline kernel source, so you'll likely have to build your own kernel by following the instructions on that page.

**Comment by pickfire** [comment]
I had asked in the irc channel of archlinux-arm, they said that it is incomplete and it isn't included so far.
Thanks for your help.

Good luck and have a nice day!
