### ISSUE TITLE
xwayland: focus on wrong (not displayed) window

### ISSUE THREAD

**Issue by jorsn** [michaelforney/velox#22]
When I have multiple xwayland clients running with different tags focus jumps over to the most recently opened window again and again. So I am looking at window A with tag 1 while typing or clicking in window B with tag 2. Sometimes keyboard input goes to window A wile mouse input goes to window B.

I can restore correct focus by applying tag 1 to window B, moving focus to window A and then applying tag 2 to window B again. Window A is then focused but only for a short time after which I need to repeat the procedure.

**Comment by michaelforney** [comment]
xwayland support was removed from swc.
