### ISSUE TITLE
kmscon

### ISSUE THREAD

**Issue by 257** [michaelforney/velox#23]
can't run velox with kmscon. this is how getty@.service service is setup here:

```
[Service]
ExecStart=
ExecStart=/usr/bin/kmscon -v "--vt=%I" --drm --hwaccel --no-switchvt --seats=seat0 --session-control --login -- /bin/login -p -f user %I $TERM
Environment='XDG_VTNR=%I'
Restart=on-success
#EnvironmentFile=/etc/kmscon/env
```

and this is what happens when i try to run swc-launch to get velox working:

```
use@machine:~ swc-launch -- env LD_LIBRARY_PATH=$HOME/.local/lib velox
open /dev/tty0: Permission denied
```

**Comment by michaelforney** [comment]
Is your swc-launch setuid and owned by root? It needs to be able to open `/dev/tty0` so it can find an open VT.

**Comment by 257** [comment]
works fine! gentoo must have changed their installations and added the suid on the file:
```
host:~ stat -c "%a %A %n" $(which swc-launch) 
4711 -rws--x--x /usr/bin/swc-launch
```

closing.
