### ISSUE TITLE
Launching Velox

### ISSUE THREAD

**Issue by DmitryHetman** [michaelforney/velox#25]
How to launch velox?
I've tried 
$ velox
[swc:libswc/swc.c: 123] ERROR: Could not connetct to swc-launch

and:

$ swc-launch velox
running on /dev/tty7
[swc:libswc/drm.c:149] DEBUG: /dev/dri/card0 is primary GPU
\#find driver: Trying DRM driver 'intel'
Using config at '/home/dmitry/.velox.conf

both doesn't work.
Weston works fine.
GPU: Intel HD 4600
Linux: 4.9_rc6
wayland: 1.12.0
wayland-protocols: 1.7

**Comment by DmitryHetman** [comment]
Hey! How to launch it?

**Comment by michaelforney** [comment]
`swc-launch velox` is the right way.

You say it "doesn't work". Can you provide more details?

**Comment by DmitryHetman** [comment]
Seems like it starts working, I see empty screen, and it immediately crashes without any output.

**Comment by michaelforney** [comment]
I can't help you without more information like a gdb backtrace.

**Comment by DmitryHetman** [comment]
Ok, also I can't launch it even in weston:

[velox.txt](https://github.com/michaelforney/velox/files/856662/velox.txt)

**Comment by michaelforney** [comment]
That error message says that another compositor is running on `wayland-0`. Run `swc-launch -s wayland-1 velox` if you want to listen on a different socket.

**Comment by DmitryHetman** [comment]
Velox works now.
