### ISSUE TITLE
Failed to launch GTK3 apps.

### ISSUE THREAD

**Issue by DmitryHetman** [michaelforney/velox#32]
All gtk 3 apps shows same issue:
[velox.log.txt](https://github.com/michaelforney/velox/files/921167/velox.log.txt)

Also, in sway it works just fine.
Is it becouse swc-launch does not supports xdg_shell_v6 ?

**Comment by DmitryHetman** [comment]
velox must switch to xdg_shell_v6.

**Comment by michaelforney** [comment]
swc now supports stable xdg-shell.
