### ISSUE TITLE
Stable and feature complete ?

### ISSUE THREAD

**Issue by ecocode** [michaelforney/velox#35]
Hello,

Before digging into installing and trying out Velox I would like to know if this software can be considered stable and feature complete ?

**Comment by DmitryHetman** [comment]
Yes, it worked good, I want to use it as well.

**Comment by michaelforney** [comment]
Really, it depends on your what you need out of it.

velox can be considered stable and feature complete, but swc is lacking support for some new wayland interfaces, and wld only has hardware acceleration for a limited set of GPUs.
