### ISSUE TITLE
Webkit2gtk crashes on opening contextmenu

### ISSUE THREAD

**Issue by sdsddsd1** [michaelforney/velox#37]
Webkit2gtk crashes on opening the contextmenu.  
There are two different error messages showing up, sometimes the one sometimes the other.
- `Error flushing display: Broken pipe`
- `Error 22 (Invalid argument) dispatching to Wayland display.`

Iam using the latest git for velox, swc and wld.
I can confirm that other wlroots compositors are working as expected.

**Comment by michaelforney** [comment]
I believe this is an issue with lack of xdg_positioner support in the xdg_shell implementation. swc used to support xdg_popup with xdg-shell-unstable-v5, which had a simple interface. With stable xdg_shell, it got a lot more complicated with xdg_positioner.

At the very least, swc should implement stubs so it doesn't crash.

**Comment by michaelforney** [comment]
Reopened this issue on the swc issue tracker, so closing this.
