### ISSUE TITLE
No windows rendered?

### ISSUE THREAD

**Issue by landgraf** [michaelforney/velox#38]
I've built wld/swc/velox.
Velox starts on tty2 with default config but I was not able to use it as it remains silent :(
No windows rendered, nor terminal/dmenu started. I tried to change st to urxvt/xterm/emacs without success. 
Win-Shift-Q works fine thought.

**Comment by michaelforney** [comment]
You need to use a terminal that supports Wayland.

swc does not currently support Xwayland (it used to, but it was removed since I don't use it). But, several users have asked about re-adding it so I may do that at some point.

**Comment by landgraf** [comment]
Thank you. Terminology works. 
Default config should be updated probably :)
