### ISSUE TITLE
So, how do i run it?

### ISSUE THREAD

**Issue by ghost** [michaelforney/velox#41]
i'm trying to run it from the tty but  i get "Could not open display"

**Comment by InfiniteWorldSoftware** [comment]
Do you have a Nvidia GPU? If so, Velox won't work on your machine. Also, just typing in `velox` won't do the trick- you need to run the command `swc-launch velox`.

**Comment by DaniV5** [comment]
eeeh

**Comment by InfiniteWorldSoftware** [comment]
What was that? Did it work?

**Comment by DaniV5** [comment]
no, i need this swc stuff
maybe i should just wait for wayland to have better support for stuff really
i'm breaking my head trying to find something useful

**Comment by InfiniteWorldSoftware** [comment]
`swc` is a library written by the author of this window manager. You can download it from GitHub (I believe he links it in the README.md) and compile it.
