### ISSUE TITLE
Doesn't working on Void Linux

### ISSUE THREAD

**Issue by crzjp** [michaelforney/velox#44]
I followed all the installation steps of velox and its dependencies, but when starting it I get the following error:

  ```
  running on /dev/tty2
  [swc:libswc/drm.c:152] DEBUG: /dev/dri/card0 is the primary GPU
  # find_driver: Trying DRM driver `intel'
  [swc:libswc/drm.c:283] ERROR: Could not create WLD DRM renderer
  [swc:libswc/swc.c:126] ERROR: Could not initialize DRM
```
My .profile:

```
#!/usr/bin/env sh

export PATH=$PATH:~/.local/bin:~/.local/bin/color-scripts:~/.cargo/bin

if [ "$(tty)" = "/dev/tty1" ]; then
        export QT_QPA_PLATFORM=xcb
        startx
fi

if [ "$(tty)" = "/dev/tty2" ]; then
        export QT_QPA_PLATFORM=wayland
        export XDG_SESSION_TYPE=wayland
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        swc-launch velox
fi
```

My system/hardware info:

OS: Void Linux
Init system: Runit
Mesa driver version: mesa-dri-20.3.4_1 
Elogind version: elogind-246.9.2_1

**Comment by michaelforney** [comment]
My best guess is that your GPU is newer than the ones currently supported by wld's intel driver. Check lspci to see which one you have.

Try synchronizing https://github.com/michaelforney/wld/blob/master/intel/i965_pci_ids.h with the one from mesa.

Or, set WLD_DRM_DUMB=1 in your environment to use software rendering, which works on any GPU with a DRM driver.

**Comment by crzjp** [comment]
I don't think my GPU is new (2011 btw), but here's the lspci output:
```
$ lspci | grep Graph
00:02.0 VGA compatible controller: Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
00:02.1 Display controller: Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
```
I tried your third option and worked. Thank you so much.

**Comment by michaelforney** [comment]
Hmm, maybe it's too old then? The integrated GPU on my 2011 laptop works fine, but I've never tried on an Atom.

What are the PCI IDs (check `lspci -nn`)?
