### ISSUE TITLE
Velox doesn't start at all

### ISSUE THREAD

**Issue by PalanixYT** [michaelforney/velox#46]
When i run swc-launch velox Velox doesn't start at all, giving this output: `running on /dev/tty2 (WW) Option "-listen" for file descriptors is deprecatedary Please use "-listenfd" instead. (WW) Option "-listen" for file descriptors is deprecated Please use "-listenfd" instead. glamor: no eglstream capable devices found (EE) could not connect to wayland server`

**Comment by michaelforney** [comment]
Hi, I already transferred your previous issue to swc: https://github.com/michaelforney/swc/issues/67

Please continue there.

**Comment by PalanixYT** [comment]
oh sorry, I didn't notice that
