### ISSUE TITLE
How can I set my keyboard layout?

### ISSUE THREAD

**Issue by stapelberg** [michaelforney/velox#8]
With weston, I can use the following entry in `~/.config/weston.ini`:

```text
[keyboard]
keymap_layout=de
keymap_variant=neo
```

After reading `config.c` and grepping through the rest of the source, I don’t think this is possible in velox, or is it? Is there a way I can do this outside of velox, and if so, how? Otherwise, could you please implement that feature? Not being able to use the layout I’m accustomed to is a blocker for me :).

Thank you.

**Comment by krobelus** [comment]
You can set the XKB_DEFAULT_LAYOUT, XKB_DEFAULT_VARIANT and XKB_DEFAULT_OPTIONS environment variables before launching velox.

**Comment by stapelberg** [comment]
@krobelus Thanks, that works.

I’m still wondering whether that’s the intended way to configure the keyboard layout or whether velox should eventually gain support for specifying the keyboard layout in the velox config file…?

**Comment by michaelforney** [comment]
Yes, this is the intended way to configure the keyboard layout. Since this is dealt with internally by libxkbcommon, I see no reason to add extra config file options.
